import React from 'react';
import { motion } from 'framer-motion';
import { Card } from '../ui/Card';
import { Button } from '../ui/Button';
import { Download, FileText, Share2, Smartphone, Printer, Send } from 'lucide-react';
import { LessonPack } from '../../types';
import jsPDF from 'jspdf';

interface ExportOptionsProps {
  lessonPack: LessonPack;
}

export const ExportOptions: React.FC<ExportOptionsProps> = ({ lessonPack }) => {
  const exportTeacherGuide = () => {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    
    // Title
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('ASman Learning - Teacher Guide', margin, 30);
    
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text(lessonPack.title, margin, 50);
    
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, 65);
    
    let yPosition = 85;
    
    // Lesson Content
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Lesson Content', margin, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    const contentLines = pdf.splitTextToSize(lessonPack.simplifiedExplanation, pageWidth - 2 * margin);
    pdf.text(contentLines, margin, yPosition);
    yPosition += contentLines.length * 5 + 20;
    
    // Teacher Notes
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Teacher Notes', margin, yPosition);
    yPosition += 15;
    
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    const notesLines = pdf.splitTextToSize(lessonPack.teacherNotes, pageWidth - 2 * margin);
    pdf.text(notesLines, margin, yPosition);
    
    pdf.save(`${lessonPack.title.replace(/\s+/g, '-').toLowerCase()}-teacher-guide.pdf`);
  };

  const exportStudentNotes = () => {
    const content = `
${lessonPack.title}
Student Notes

Key Points:
${lessonPack.simplifiedExplanation.replace(/\[AI DRAWS:.*?\]/g, '').trim()}

Activity: ${lessonPack.handsOnTask.title}
Materials: ${lessonPack.handsOnTask.materials.join(', ')}

Questions to Think About:
${lessonPack.aiQA.map((qa, index) => `${index + 1}. ${qa.question}`).join('\n')}

Generated by ASman Learning - AI Whiteboard Assistant
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${lessonPack.title.replace(/\s+/g, '-').toLowerCase()}-student-notes.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const shareToWhatsApp = () => {
    const message = `🎓 ASman Learning Lesson: ${lessonPack.title}

📚 Key Points:
${lessonPack.simplifiedExplanation.substring(0, 200)}...

🎯 Activity: ${lessonPack.handsOnTask.title}

Generated by ASman Learning - AI Whiteboard Assistant for Teachers`;
    
    const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  return (
    <Card>
      <div className="bg-gradient-to-r from-green-500 to-green-600 p-4 text-white">
        <div className="flex items-center space-x-3">
          <Download className="w-6 h-6" />
          <h3 className="text-lg font-semibold">Export & Share Your Lesson</h3>
        </div>
      </div>
      <div className="p-6">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
          <Button
            onClick={exportTeacherGuide}
            variant="primary"
            className="flex items-center justify-center space-x-2"
          >
            <FileText className="w-5 h-5" />
            <span>Teacher Guide PDF</span>
          </Button>
          
          <Button
            onClick={exportStudentNotes}
            variant="secondary"
            className="flex items-center justify-center space-x-2"
          >
            <FileText className="w-5 h-5" />
            <span>Student Notes</span>
          </Button>
          
          <Button
            onClick={shareToWhatsApp}
            variant="outline"
            className="flex items-center justify-center space-x-2"
          >
            <Smartphone className="w-5 h-5" />
            <span>Share to WhatsApp</span>
          </Button>
        </div>

        {/* Export Features */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-4 bg-blue-50 rounded-lg">
            <h4 className="font-bold text-blue-800 mb-3 flex items-center">
              <Printer className="w-5 h-5 mr-2" />
              For Teachers:
            </h4>
            <ul className="text-sm text-blue-700 space-y-1">
              <li>• Complete lesson plan with AI cues</li>
              <li>• Voice command reference guide</li>
              <li>• Global module integration notes</li>
              <li>• Student interaction guidelines</li>
            </ul>
          </div>
          
          <div className="p-4 bg-green-50 rounded-lg">
            <h4 className="font-bold text-green-800 mb-3 flex items-center">
              <Send className="w-5 h-5 mr-2" />
              For Students & Parents:
            </h4>
            <ul className="text-sm text-green-700 space-y-1">
              <li>• Simplified lesson summary</li>
              <li>• Key concepts and activities</li>
              <li>• Questions for home discussion</li>
              <li>• WhatsApp-friendly format</li>
            </ul>
          </div>
        </div>
        
        <div className="mt-6 p-4 bg-orange-50 rounded-lg">
          <p className="text-sm text-orange-700 text-center">
            📱 <strong>Teacher Tip:</strong> Share student notes via WhatsApp to keep parents informed about what their children learned today!
          </p>
        </div>
      </div>
    </Card>
  );
};